[project]
name = "dropkeys"
version = "0.1.0"
description = "Share Environment Variables Securely"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "base58>=2.1.1",
    "psycopg2-binary>=2.9.12",
    "pycryptodome>=3.23.0",
    "pydantic-settings>=2.14.0",
    "reflex>=0.9.0",
    "reflex-google-auth>=0.2.0",
    "sqlalchemy>=2.0.49",
    "upstash-redis>=1.7.0",
]
